name: Run Robot Framework Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install robotframework
      - name: Run tests
        run: AO_CA/
